export default [
   { label: "Character Varying (VARCHAR)", value: "VARCHAR" },
   { label: "Character (CHAR)", value: "CHAR" },
   { label: "Text (TEXT)", value: "TEXT" },
   { label: "Small Integer (SMALLINT)", value: "SMALLINT" },
   { label: "Integer (INTEGER)", value: "INTEGER" },
   { label: "Big Integer (BIGINT)", value: "BIGINT" },
   { label: "Serial (SERIAL)", value: "SERIAL" },
   { label: "Big Serial (BIGSERIAL)", value: "BIGSERIAL" },
   { label: "Numeric (NUMERIC)", value: "NUMERIC" },
   { label: "Real (REAL)", value: "REAL" },
   { label: "Double Precision (DOUBLE PRECISION)", value: "DOUBLE PRECISION" },
   { label: "Boolean (BOOLEAN)", value: "BOOLEAN" },
   { label: "UUID", value: "UUID" },
   { label: "Date (DATE)", value: "DATE" },
   { label: "Time (TIME)", value: "TIME" },
   { label: "Timestamp (TIMESTAMP)", value: "TIMESTAMP" },
   { label: "Timestamp with Timezone (TIMESTAMPTZ)", value: "TIMESTAMPTZ" },
   { label: "Interval (INTERVAL)", value: "INTERVAL" },
   { label: "JSON", value: "JSON" },
   { label: "JSONB (Binary JSON)", value: "JSONB" },
   { label: "Array (ARRAY)", value: "ARRAY" },
   { label: "HStore (Key-Value Store)", value: "HSTORE" },
   { label: "CIDR (Network Address)", value: "CIDR" },
   { label: "INET (IP Address)", value: "INET" },
   { label: "MAC Address (MACADDR)", value: "MACADDR" },
   { label: "Bit String (BIT)", value: "BIT" },
   { label: "Bit Varying (VARBIT)", value: "VARBIT" },
   { label: "Point (POINT)", value: "POINT" },
   { label: "Line (LINE)", value: "LINE" },
   { label: "LSEG (Line Segment)", value: "LSEG" },
   { label: "Box (BOX)", value: "BOX" },
   { label: "Path (PATH)", value: "PATH" },
   { label: "Polygon (POLYGON)", value: "POLYGON" },
   { label: "Circle (CIRCLE)", value: "CIRCLE" },
   { label: "TSVector (Full Text Search Vector)", value: "TSVECTOR" },
   { label: "TSQuery (Full Text Search Query)", value: "TSQUERY" },
   { label: "Money (MONEY)", value: "MONEY" },
   { label: "XML", value: "XML" },
];
